export const COMMANDS_BY_LANG = {
  uz: [
    { command: 'start',    description: 'Botni ishga tushirish' },
    { command: 'report',   description: 'Oylik hisobot' },
    { command: 'today',    description: 'Bugungi balans' },
    { command: 'balance',  description: 'Joriy balans' },
    { command: 'income',   description: 'Kirimlar' },
    { command: 'expense',  description: 'Chiqimlar' },
    { command: 'top',      description: 'Top kategoriyalar' },
    { command: 'switch',   description: 'Workspace almashtirish' },
    { command: 'settings', description: 'Sozlamalar' },
    { command: 'lang',     description: "Tilni o'zgartirish" },
    { command: 'invite',   description: 'Jamoaga taklif qilish' },
    { command: 'help',     description: 'Yordam' },
  ],
  ru: [
    { command: 'start',    description: 'Запустить бот' },
    { command: 'report',   description: 'Отчёт за месяц' },
    { command: 'today',    description: 'Баланс сегодня' },
    { command: 'balance',  description: 'Текущий баланс' },
    { command: 'income',   description: 'Доходы' },
    { command: 'expense',  description: 'Расходы' },
    { command: 'top',      description: 'Топ категорий' },
    { command: 'switch',   description: 'Сменить счёт' },
    { command: 'settings', description: 'Настройки' },
    { command: 'lang',     description: 'Изменить язык' },
    { command: 'invite',   description: 'Пригласить в команду' },
    { command: 'help',     description: 'Справка' },
  ],
  en: [
    { command: 'start',    description: 'Start the bot' },
    { command: 'report',   description: 'Monthly report' },
    { command: 'today',    description: "Today's balance" },
    { command: 'balance',  description: 'Current balance' },
    { command: 'income',   description: 'Income' },
    { command: 'expense',  description: 'Expenses' },
    { command: 'top',      description: 'Top categories' },
    { command: 'switch',   description: 'Switch account' },
    { command: 'settings', description: 'Settings' },
    { command: 'lang',     description: 'Change language' },
    { command: 'invite',   description: 'Invite to team' },
    { command: 'help',     description: 'Help' },
  ],
} as const;
